#' setup a new directory
#'
#' Sets up directory structure needed for recount3 to read data in.
#' Note that `recount3` only currently works with *human* or *mouse*,
#' so regardless your *actual* organism you used, you must choose
#' one of those two to make this work.
#'
#' @param base_dir the top level directory where projects should live
#' @param short_id the short identifier used when unifying your outputs
#'
#' @export
#' @import cli
#' @import fs
#' @return project directory list
rc3_setup_directory = function(
  base_dir = ".",
  short_id = "test",
  organism = "human"
) {
  if (base_dir == ".") {
    base_dir = getwd()
  }
  dir_exists = fs::dir_exists(base_dir)

  if (dir_exists) {
    cli::cli_alert_info(
      "Using {.val {base_dir}} to create underlying folders ..."
    )
  } else {
    cli::cli_alert_info(
      "Creating new directory {.val {base_dir}} to create underlying folders ..."
    )
    fs::dir_create(base_dir)
  }

  all_dirs = .list_sources_annotations_dirs(base_dir, organism, short_id)
  cli::cli_alert_info("Creating directories: {.val {all_dirs}}")
  fs::dir_create(all_dirs, recurse = TRUE)
  return(invisible(all_dirs))
}

#' Copy Unify Output
#'
#' Copy the output generated by the unify script, to the setup directory,
#' and symlink a few things. Note that `recount3` is expecting *human* or *mouse*,
#' with the relevant annotation. If you are using this, you could have generated
#' anything you wanted (I build this to handle *zebrafish* using *MZ11*). Therefore,
#' it copies the files, then symlinks them to the names that `recount3` expects.
#'
#' @param rc3_directory where you want things copied to (sort of)
#' @param short_id the short id of the project
#' @param unify_directory where the unify outputs are stored
#' @param references_directory where the reference data is stored
#' @param organism what organism is the data (for real or pretend)
#' @param annotation what annotations are we interested in (for real or pretend)
#'
#' @export
#' @return NULL, invisibly
rc3_copy_unify_outputs = function(
  rc3_directory = NULL,
  short_id = "test",
  unify_directory = NULL,
  references_directory = NULL,
  organism = "human",
  annotation = "G026"
) {
  if (is.null(unify_directory)) {
    cli::cli_abort(
      "{.val unify_directory} is `NULL`. Please supply a {.val unify_directory}."
    )
  }
  if (is.null(rc3_directory)) {
    cli::cli_abort(
      "{.val rc3_directory} is `NULL`. Please supply a {.val rc3_directory}."
    )
  }
  if (is.null(references_directory)) {
    cli::cli_abor(
      "{.val references_directory is `NULL`. Please supply a {.val references_directory}."
    )
  }
  if (length(rc3_directory) == 1) {
    dir_exists = fs::dir_exists(rc3_directory)
    if (dir_exists) {
      all_dirs = fs::path(
        rc3_directory,
        .list_sources_annotations_dirs(short_id)
      )
    }
  }
  if (length(rc3_directory) == 7) {
    all_dirs = rc3_directory
    if (!.check_shortid(all_dirs, short_id)) {
      cli::cli_abort(
        "{.val {short_id}} is not in at least 5 paths in {.val rc3_directory}!"
      )
    }
  }

  unify_exist = fs::dir_exists(unify_directory)
  if (!unify_exist) {
    cli::cli_abort("{.val unify_directory {unify_directory} doesn't exist!")
  }
  copy_list = .copy_list()
  ref_files = fs::dir_ls(
    references_directory,
    recurse = TRUE,
    regexp = "[exon_sums|gene_sums].*.gtf.gz",
  )
  if (length(ref_files) >= 2) {
    cli::cli_abort(
      "Please check the contents of {.val {references_directory}} to make sure the 'exon_sums' and 'gene_sums' files exist!"
    )
  }
  purrr::iwalk(copy_list, \(source_dir, dest_desc) {
    # print(source_dir)
    # print(dest_desc)
    if (grepl("data_sources", dest_desc)) {
      dest_dir = all_dirs[dest_desc]
      full_source = fs::path(unify_directory, source_dir)
      fs::dir_copy(full_source, dest_dir, overwrite = TRUE)
    } else {
      dest_dir = all_dirs[dest_desc]

      full_source = grep(source_dir, ref_files, value = TRUE)
      just_file = fs::path_file(full_source)
      dest_file = fs::path(dest_dir, just_file)
      fs::file_copy(full_source, dest_file)
    }
  })

  metadata_file = fs::dir_ls(
    all_dirs,
    recurse = TRUE,
    regexp = "recount_project"
  )
  metadata_dir = grep("metadata$", all_dirs, value = TRUE)
  new_file = paste0(short_id, ".recount_project.MD.gz")
  fs::file_copy(metadata_file, fs::path(metadata_dir, new_file))

  create_annotation_sum_links(
    all_dirs,
    organism = organism,
    annotation = annotation
  )

  return(invisible(NULL))
}


create_annotation_sum_links = function(
  all_dirs,
  organism = "human",
  annotation = "G026"
) {
  annotation_files = fs::dir_ls(
    all_dirs,
    recurse = TRUE,
    regexp = "annotations.*.gtf.gz",
    type = "file"
  ) |>
    unique()

  annotation_gene = grep("gene_sums", annotation_files, value = TRUE)
  gene_file = fs::path(
    fs::path_dir(annotation_gene),
    paste0(organism, ".gene_sums.", annotation, ".gtf.gz")
  )
  fs::link_create(annotation_gene, gene_file)

  annotation_exon = grep("exon_sums", annotation_files, value = TRUE)
  exon_file = fs::path(
    fs::path_dir(annotation_exon),
    paste0(organism, ".exon_sums.", annotation, ".gtf.gz")
  )
  fs::link_create(annotation_exon, exon_file)

  sums_files = fs::dir_ls(
    all_dirs,
    recurse = TRUE,
    regexp = "data_sources.*._sums",
    type = "file"
  ) |>
    unique()
  sum_genes = grep(
    "gene_sums",
    grep("SIRV|ERCC", sums_files, invert = TRUE, value = TRUE),
    value = TRUE
  )
  gene_file = fs::path(
    fs::path_dir(sum_genes),
    replace_annotation(fs::path_file(sum_genes), annotation)
  )
  fs::link_create(sum_genes, gene_file)

  sum_exons = grep(
    "exon_sums",
    grep("SIRV|ERCC", sums_files, invert = TRUE, value = TRUE),
    value = TRUE
  )

  exon_file = fs::path(
    fs::path_dir(sum_exons),
    replace_annotation(fs::path_file(sum_exons), annotation)
  )
  fs::link_create(sum_exons, exon_file)
  return(invisible(NULL))
}

replace_annotation = function(in_file, annotation = "G026") {
  # in_file = "chd7bulk.gene_sums.chd7bulk.MZ11.gz"
  # annotation = "G026"
  split_file = stringr::str_split(in_file, "\\.")[[1]]
  split_file[4] = annotation
  paste0(split_file, collapse = ".")
}

.list_sources_annotations_dirs = function(base_dir, organism, short_id) {
  use_dirs = list(
    data_sources = c(
      "base_sums",
      "exon_sums",
      "gene_sums",
      "junctions",
      "metadata"
    ),
    annotations = c("gene_sums", "exon_sums")
  )

  dir_ids = unlist(use_dirs)
  all_dirs = fs::path(
    base_dir,
    organism,
    c(
      fs::path("data_sources", short_id, use_dirs$data_sources),
      fs::path("annotations", use_dirs$annotations)
    )
  )

  all_names = paste0(
    rep(names(use_dirs), purrr::map_int(use_dirs, length)),
    ".",
    dir_ids
  )
  names(all_dirs) = all_names
  return(all_dirs)
}

.check_shortid = function(paths, short_id) {
  split_paths = fs::path_split(paths)

  short_in_path = purrr::map(split_paths, \(in_path) {
    length(in_path) - which(in_path %in% short_id)
  }) |>
    purrr::list_c()
  if (sum(short_in_path %in% 1) >= 5) {
    return(TRUE)
  } else {
    return(FALSE)
  }
}

.check_unify = function(unify_dir) {}

.copy_list = function() {
  c(
    "data_sources.exon_sums" = "exon_sums_per_study",
    "data_sources.gene_sums" = "gene_sums_per_study",
    "data_sources.junctions" = "junction_counts_per_study",
    "data_sources.metadata" = "metadata",
    "annotations.gene_sums" = "gene_sums.*.gtf.gz",
    "annotations.exon_sums" = "exon_sums.*.gtf.gz"
  )
}
